# Generated by Django 3.2.13 on 2023-11-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaster',
            name='name',
            field=models.CharField(choices=[('Floods', 'Floods'), ('Drought', 'Drought'), ('Fire', 'Fire'), ('Cyclone', 'Cyclone'), ('Other', 'Other')], max_length=100),
        ),
    ]
