# Generated by Django 3.2.13 on 2023-11-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_disaster_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaster',
            name='dead',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disaster',
            name='displaced',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
