# Generated by Django 3.2.13 on 2023-11-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20231126_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaster',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='banner_image'),
        ),
        migrations.AddField(
            model_name='disaster',
            name='image_one',
            field=models.ImageField(blank=True, null=True, upload_to='data_images/'),
        ),
        migrations.AddField(
            model_name='disaster',
            name='image_three',
            field=models.ImageField(blank=True, null=True, upload_to='data_images/'),
        ),
        migrations.AddField(
            model_name='disaster',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to='data_images/'),
        ),
    ]
