# Generated by Django 3.2.13 on 2023-11-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_affectedarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaster',
            name='affected_areas',
            field=models.ManyToManyField(to='core.AffectedArea'),
        ),
    ]
