# Generated by Django 3.2.13 on 2023-11-28 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_disaster_affected_areas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disaster',
            name='affected_areas',
        ),
        migrations.AddField(
            model_name='disaster',
            name='affected_areas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.affectedarea'),
            preserve_default=False,
        ),
    ]
