# Generated by Django 3.2.13 on 2023-11-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20231128_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disaster',
            name='affected_areas',
        ),
        migrations.AddField(
            model_name='disaster',
            name='affected_areas',
            field=models.ManyToManyField(to='core.AffectedArea'),
        ),
    ]
