# Generated by Django 3.2.13 on 2024-02-25 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
